### (1) 화면상에서 pytorch 에서 데이터를 저장하는 단위는 (tensor) 입니다.

### 
(2) 텐서의 경우 torch 를 통해 생성할 수 있으며 cuda 를 지원하는 그래픽카드에서도 해당 데이터 저장단위를 로딩할 수 있습니다.  
 텐서에서 shape (크기), size() (크기메서드), ndim (차원), dtype (데이터타입), is_contiguous() (데이터가 메모리상에서 연속저장 여부), contiguous() (연속저장 기능), T (transpose), data_ptr() 데이터 포인터, view() (메모리 연속적으로 저장시 텐서 저장 차원 형태를 변경), reshape() 메모리에서의 저장 형태와 관련 없이 텐서의 차원 형태 변경 등등이 있씁니다

(3) 정수형 데이터 저장방식 (numpy와 유사)

- torch.int8
- torch.int16
- torch.int32
- torch.int64
- torch.uint8
- torch.uint16
- torch.uint32
- torch.uint64
등등이 있습니다.  

u 가 붙은 것은 양의 정수 (0~비트수만큼) 만큼 저장가능하며  
u 가 생략된 데이터 타입은 음의 정수 만큼 저장 가능합니다.  
(-2^(비트수-1)~ [2^(비트수-1) -1]) 까지 저장가능합니다.


In [12]:

import torch

### (4) 문제

In [13]:
tbool = torch.tensor(
    [
        10,
        -5,
        1.4,
        7,
        0,
        -1,
        0
],
 dtype=torch.bool
 )

tbool.shape, tbool.size(), tbool.ndim, tbool.dtype, tbool.is_contiguous(), tbool.contiguous(), tbool.data_ptr()

attributes = ['shape', 'size',  'ndim', 'dtype', 'is_contiguous', 'contiguous', 'data_ptr']
for attr in attributes:
    try:
        print(f'{attr} : {getattr(tbool, attr)()}')
    except:
        print(f'{attr} : {getattr(tbool, attr)}')



shape : torch.Size([7])
size : torch.Size([7])
ndim : 1
dtype : torch.bool
is_contiguous : True
contiguous : tensor([ True,  True,  True,  True, False,  True, False])
data_ptr : 91186432


### (5) 문제

In [14]:
data = torch.zeros((2,5))
data

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

### (6) 문제

In [15]:
eye5 = torch.eye(5)
eye5

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

### (7) 문제

In [16]:
eye5as3 = eye5 * 3
eye5as3

tensor([[3., 0., 0., 0., 0.],
        [0., 3., 0., 0., 0.],
        [0., 0., 3., 0., 0.],
        [0., 0., 0., 3., 0.],
        [0., 0., 0., 0., 3.]])

### (8) 문제

In [17]:
import numpy

intermidate = numpy.arange(7,101,7).astype(numpy.float32)
ans8 = torch.from_numpy(intermidate)
ans8

tensor([ 7., 14., 21., 28., 35., 42., 49., 56., 63., 70., 77., 84., 91., 98.])

In [18]:
image = torch.randint(0,255, (1, 3, 120, 80)).type(torch.uint8)
image[0, 0, 0, :].shape


torch.Size([80])

### (10) 문제

In [19]:
# (1)

oneD = torch.randint(1,100,(10,))

# (2)
threeD = oneD.reshape(1,2,5)

# (3)
threeDT = torch.transpose(threeD, 0, 2)

# (4)
threeDPermute = torch.permute(threeD, (2,0,1))

for x in [oneD, threeD, threeDT, threeDPermute]:
    print(x.shape)

torch.Size([10])
torch.Size([1, 2, 5])
torch.Size([5, 2, 1])
torch.Size([5, 1, 2])


### (11) 문제

In [20]:
import pandas as pd

# (1)
datadf = pd.DataFrame(
    {
        '국어' : [90,70,80],
        '영어' : [70,100,80],
        '수학' : [99,88,77],
    }
)

#(2)

print(f"과목별 합계 \n{datadf.sum()}")
print(f"과목별 평균 \n{datadf.mean()}")
print(f"과목별 최고점수 \n{datadf.max()}")

#(3)
print(f"개인별 합계 \n{datadf.sum(axis  = 1)}")
print(f"개인별 평균 \n{datadf.mean(axis  = 1)}")
print(f"개인별 최고점수 \n{datadf.max(axis  = 1)}")





과목별 합계 
국어    240
영어    250
수학    264
dtype: int64
과목별 평균 
국어    80.000000
영어    83.333333
수학    88.000000
dtype: float64
과목별 최고점수 
국어     90
영어    100
수학     99
dtype: int64
개인별 합계 
0    259
1    258
2    237
dtype: int64
개인별 평균 
0    86.333333
1    86.000000
2    79.000000
dtype: float64
개인별 최고점수 
0     99
1    100
2     80
dtype: int64


### (12) 문제

In [21]:
datasr2 = pd.Series([0.5,0.2,0.7])
# (1)
data2 = torch.from_numpy(datasr2.values)
data1 = torch.from_numpy(datadf.to_numpy().astype(numpy.float64))

# (2), (3)
operators = ['mul','add','div', 'sub', 'matmul']
for x in operators:
    print(f"{x} : \n{getattr(data1, x)(data2)}")


mul : 
tensor([[45.0000, 14.0000, 69.3000],
        [35.0000, 20.0000, 61.6000],
        [40.0000, 16.0000, 53.9000]], dtype=torch.float64)
add : 
tensor([[ 90.5000,  70.2000,  99.7000],
        [ 70.5000, 100.2000,  88.7000],
        [ 80.5000,  80.2000,  77.7000]], dtype=torch.float64)
div : 
tensor([[180.0000, 350.0000, 141.4286],
        [140.0000, 500.0000, 125.7143],
        [160.0000, 400.0000, 110.0000]], dtype=torch.float64)
sub : 
tensor([[89.5000, 69.8000, 98.3000],
        [69.5000, 99.8000, 87.3000],
        [79.5000, 79.8000, 76.3000]], dtype=torch.float64)
matmul : 
tensor([128.3000, 116.6000, 109.9000], dtype=torch.float64)


In [22]:
t_c = [0.5, 14.0, 15.0, 28.0, 11.0, 8.0, 3.0, -4.0, 6.0, 13.0, 21.0]
t_u = [35.7, 55.9, 58.2, 81.9, 56.3, 48.9, 33.9, 21.8, 48.4, 60.4, 68.4]
t_c = torch.tensor(t_c)
t_u = torch.tensor(t_u)

def model(t_u, w, b):
    return w * t_u + b

def loss_fn(t_p, t_c):
    squared_diffs = (t_p - t_c)**2
    return squared_diffs.mean()

w = torch.ones(())
b = torch.zeros(())

t_p = model(t_u, w, b)
loss = loss_fn(t_p, t_c)


delta = 0.1
loss_rate_of_change_w = \
(loss_fn(model(t_u, w + delta, b), t_c) -
loss_fn(model(t_u, w - delta, b), t_c)) / (2.0 * delta)



