## 텐서 결합 및 연결

In [1]:
import torch
from torch import *
import numpy as np
import intel_extension_for_pytorch as ipex

In [2]:
torch.manual_seed(10)

X = rand((92,10)) # 임의의 실수 
y = randint(0,2,(10,10)) # 임의의 정수
y_col = randint(0,2,(92,13))


X.shape, y.shape, y_col.shape

(torch.Size([92, 10]), torch.Size([10, 10]), torch.Size([92, 13]))

In [3]:
# tensor 연결 cat([텐서1, 텐서2, ....])
xy1 = torch.concat((X,y), 0)
xy2 = torch.concat((X,y_col), 1)


In [4]:
xy1.shape, xy2.shape, xy1.ndim, xy2.ndim

(torch.Size([102, 10]), torch.Size([92, 23]), 2, 2)

In [5]:
x = FloatTensor([1,4])
y = FloatTensor([2,5])
z = FloatTensor([3,6])

stack([x,y,z])

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])

In [6]:
xy1.max(dim=0), xy1.shape

(torch.return_types.max(
 values=tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]),
 indices=tensor([93, 96, 92, 92, 93, 93, 93, 92, 93, 92])),
 torch.Size([102, 10]))

In [7]:
# 행 단위로 최대값 및 최대값의 인덱스 
max_value = xy1.max(dim=1)[0]
max_index = xy1.max(dim=1)[1]
max_value, max_index

(tensor([0.9693, 0.9849, 0.7192, 0.9502, 0.8988, 0.9829, 0.9619, 0.9792, 0.9894,
         0.9811, 0.9259, 0.8371, 0.9271, 0.9510, 0.9799, 0.8823, 0.8099, 0.9714,
         0.9874, 0.9061, 0.9199, 0.9623, 0.9223, 0.8031, 0.7495, 0.9382, 0.8605,
         0.8914, 0.9910, 0.9322, 0.7865, 0.9510, 0.9949, 0.9986, 0.9515, 0.7932,
         0.9093, 0.9622, 0.8867, 0.9207, 0.9259, 0.9476, 0.9829, 0.8813, 0.9480,
         0.7020, 0.9915, 0.9950, 0.8539, 0.7335, 0.9498, 0.9047, 0.8764, 0.9652,
         0.7585, 0.8418, 0.8942, 0.9911, 0.9708, 0.8443, 0.9832, 0.8314, 0.8869,
         0.9692, 0.9818, 0.9729, 0.9687, 0.9477, 0.9635, 0.9909, 0.8587, 0.8130,
         0.9211, 0.9422, 0.9526, 0.9978, 0.9640, 0.8251, 0.9529, 0.8139, 0.9176,
         0.9107, 0.9245, 0.8931, 0.5992, 0.9667, 0.9151, 0.9490, 0.9520, 0.9941,
         0.9670, 0.8700, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
         1.0000, 1.0000, 1.0000]),
 tensor([7, 5, 9, 6, 1, 1, 5, 0, 7, 1, 2, 9, 0, 7, 1, 8, 5, 4, 3, 7, 6, 0,

In [8]:
# 열 단위로 최대값 및 최대값의 인덱스 
max_value = xy1.max(dim=0)[0]
max_index = xy1.max(dim=0)[1]
max_value, max_index

(tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]),
 tensor([93, 96, 92, 92, 93, 93, 93, 92, 93, 92]))

In [9]:
import pandas as pd

data = pd.DataFrame({'A':[1,2,3], 'B':[4,5,6], 'C':[7,8,9]})
data


2024-03-13 09:01:47,356 - numexpr.utils - INFO - NumExpr defaulting to 8 threads.


A  B  C
0  1  4  7
1  2  5  8
2  3  6  9

In [10]:
# 집계함수의 경우 axis 가 반대로 적용됨

data.max(axis=0), data.max(axis=1)

(A    3
 B    6
 C    9
 dtype: int64,
 0    7
 1    8
 2    9
 dtype: int64)

### Tensor 차원/형태 변경


In [11]:
t1 = tensor(
    [
        [
            [1,2,], 
            [11,22,],
            [44,55,]
        ]
    ]
)


In [12]:
t1.shape, t1.ndim

(torch.Size([1, 3, 2]), 3)

In [13]:
# transpose는 두 차원만 서로 교환가능
t11 = t1.transpose(0,1)

In [14]:
# permute 를 활용하여 차원의 순서 변경
t22 = t1.permute(1,2,0)

In [15]:
# 차원 변동이 있다고 하더라도 데이터의 주소는 변화하지 않음
t1.data_ptr(), t11.data_ptr(), t22.data_ptr()

(145891392, 145891392, 145891392)

In [16]:
t1.shape, t1[None].shape, t1[None].data_ptr()


(torch.Size([1, 3, 2]), torch.Size([1, 1, 3, 2]), 145891392)