### Tensor shape 변경
- reshape(), view() : 원소 개수가 유지됨, 기존의 텐서를 공유함

### (1) 모듈 로딩 

In [1]:
from torch import *
import intel_extension_for_pytorch as ipex

In [3]:
t1 = tensor(
    [
        [1,2,3],
        [4,5,6]
    ]
)
print(t1.shape, t1.ndim)

torch.Size([2, 3]) 2


In [9]:
t1.reshape((3,2))

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [13]:
t1.view((3,2))

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [15]:
t1.reshape((6,1))

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])