## 텐서(Tensor) 살펴보기
- pytorch 에서 데이터 저장형
- 모델 입력 (input), 출력(output) 데이터 형태

### (1) 모듈 로딩하기

In [21]:
import torch
import numpy as np

if torch.cuda.is_available():
    from torch.cuda import *
else:
    from torch import *


- Tensor 속성 관련 함수


In [22]:
# 매개변수 : 텐서 인스턴스, 텐서 변수명
def tensor_properties(tensor, name):
    print(f'{name} 텐서의 속성')
    print(f'{name} 텐서의 데이터 타입 : {tensor.dtype}')
    print(f'{name} 텐서의 데이터 형태 : {tensor.shape}')
    print(f'{name} 텐서의 데이터 크기 : {tensor.size()}')
    print(f'{name} 텐서의 데이터 차원 : {tensor.ndim}')
    print(f'{name} 텐서의 경사하강법 여부 : {tensor.requires_grad}')
    print(f"{name} 텐서의 실 데이터 : \n{tensor.data}")
    print(f"{name} 텐서의 실행 장소 : {tensor.device}")

- Tensor 생성 (1) : 특정 데이터 타입의 텐서 생성
    * 타입별 텐서 클래스 생성자 활용
    * 예) IntTensor(), FloatTensor(), BoolTensor()

In [23]:
test = IntTensor(np.ones((3,4,5)))
tensor_properties(test, 'test')
# dir(test)



test 텐서의 속성
test 텐서의 데이터 타입 : torch.int32
test 텐서의 데이터 형태 : torch.Size([3, 4, 5])
test 텐서의 데이터 크기 : torch.Size([3, 4, 5])
test 텐서의 데이터 차원 : 3
test 텐서의 경사하강법 여부 : False
test 텐서의 실 데이터 : 
tensor([[[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]],

        [[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]],

        [[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]]], dtype=torch.int32)
test 텐서의 실행 장소 : cpu


In [24]:
t2 = BoolTensor(np.ones((3,4,5)))
tensor_properties(t2, 't2')

t2 텐서의 속성
t2 텐서의 데이터 타입 : torch.bool
t2 텐서의 데이터 형태 : torch.Size([3, 4, 5])
t2 텐서의 데이터 크기 : torch.Size([3, 4, 5])
t2 텐서의 데이터 차원 : 3
t2 텐서의 경사하강법 여부 : False
t2 텐서의 실 데이터 : 
tensor([[[True, True, True, True, True],
         [True, True, True, True, True],
         [True, True, True, True, True],
         [True, True, True, True, True]],

        [[True, True, True, True, True],
         [True, True, True, True, True],
         [True, True, True, True, True],
         [True, True, True, True, True]],

        [[True, True, True, True, True],
         [True, True, True, True, True],
         [True, True, True, True, True],
         [True, True, True, True, True]]])
t2 텐서의 실행 장소 : cpu


In [25]:
t3 = FloatTensor(np.ones((3,4,5)) / 10)
tensor_properties(t3, 't3')

t3 텐서의 속성
t3 텐서의 데이터 타입 : torch.float32
t3 텐서의 데이터 형태 : torch.Size([3, 4, 5])
t3 텐서의 데이터 크기 : torch.Size([3, 4, 5])
t3 텐서의 데이터 차원 : 3
t3 텐서의 경사하강법 여부 : False
t3 텐서의 실 데이터 : 
tensor([[[0.1000, 0.1000, 0.1000, 0.1000, 0.1000],
         [0.1000, 0.1000, 0.1000, 0.1000, 0.1000],
         [0.1000, 0.1000, 0.1000, 0.1000, 0.1000],
         [0.1000, 0.1000, 0.1000, 0.1000, 0.1000]],

        [[0.1000, 0.1000, 0.1000, 0.1000, 0.1000],
         [0.1000, 0.1000, 0.1000, 0.1000, 0.1000],
         [0.1000, 0.1000, 0.1000, 0.1000, 0.1000],
         [0.1000, 0.1000, 0.1000, 0.1000, 0.1000]],

        [[0.1000, 0.1000, 0.1000, 0.1000, 0.1000],
         [0.1000, 0.1000, 0.1000, 0.1000, 0.1000],
         [0.1000, 0.1000, 0.1000, 0.1000, 0.1000],
         [0.1000, 0.1000, 0.1000, 0.1000, 0.1000]]])
t3 텐서의 실행 장소 : cpu


- Tensor 생성 (2) : 원하는 값으로 텐서 생성 => torch.tensor()

In [52]:
# dtype 매개변수 : 원하는 데이터 타입 지정 가능
t1 = tensor(np.zeros((5,2,3,)) , dtype=torch.bool) # scaler 데이터, float32 ==> bool
tensor_properties(t1, 't1')


t1 텐서의 속성
t1 텐서의 데이터 타입 : torch.bool
t1 텐서의 데이터 형태 : torch.Size([5, 2, 3])
t1 텐서의 데이터 크기 : torch.Size([5, 2, 3])
t1 텐서의 데이터 차원 : 3
t1 텐서의 경사하강법 여부 : False
t1 텐서의 실 데이터 : 
tensor([[[False, False, False],
         [False, False, False]],

        [[False, False, False],
         [False, False, False]],

        [[False, False, False],
         [False, False, False]],

        [[False, False, False],
         [False, False, False]],

        [[False, False, False],
         [False, False, False]]])
t1 텐서의 실행 장소 : cpu


### (3) 특정 값으로 채운 텐서 ==> 0,1 등의 값

In [70]:
t1 = torch.zeros((4,5),)
tensor_properties(t1, 't1')

t1 텐서의 속성
t1 텐서의 데이터 타입 : torch.float32
t1 텐서의 데이터 형태 : torch.Size([4, 5])
t1 텐서의 데이터 크기 : torch.Size([4, 5])
t1 텐서의 데이터 차원 : 2
t1 텐서의 경사하강법 여부 : False
t1 텐서의 실 데이터 : 
tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])
t1 텐서의 실행 장소 : cpu


In [71]:
t1 = torch.ones((5,6),)
tensor_properties(t1, 't1')

t1 텐서의 속성
t1 텐서의 데이터 타입 : torch.float32
t1 텐서의 데이터 형태 : torch.Size([5, 6])
t1 텐서의 데이터 크기 : torch.Size([5, 6])
t1 텐서의 데이터 차원 : 2
t1 텐서의 경사하강법 여부 : False
t1 텐서의 실 데이터 : 
tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])
t1 텐서의 실행 장소 : cpu


In [87]:
# 이미 존재하는 텐서와 동일한 shape로 잡고 값 채우기 ==> zeros_like(), ones_like(), full_like()

In [81]:
imgT = torch.randint(10,100, (3,4))
imgT

tensor([[54, 55, 99, 76],
        [13, 47, 65, 37],
        [71, 71, 39, 51]])

In [82]:
zero_img = torch.ones_like(imgT)
zero_img

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]])

In [84]:
full_img = torch.full_like(imgT, 10)
full_img

tensor([[10, 10, 10, 10],
        [10, 10, 10, 10],
        [10, 10, 10, 10]])

In [111]:
# 대각선 방향으로 1 채우기 --> eye()
t1 = torch.eye(10,9)
t1

tensor([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

### (4) 임의의 값으로 Tensor 생성 => torch.rand(), torch.randn(), torch.randint()


### (5) ndarray 객체 활용 => torch.from_numpy(), torch.as_tensor(), tensor()

In [278]:
data = np.array([1,2,3,4,5], dtype=np.uint8)
data

array([1, 2, 3, 4, 5], dtype=uint8)

In [279]:
t1 = from_numpy(data)
t1

tensor([1, 2, 3, 4, 5], dtype=torch.uint8)

In [280]:
t2 = as_tensor(data)
t2

tensor([1, 2, 3, 4, 5], dtype=torch.uint8)

In [281]:

t3 = torch.tensor(data)
t3

tensor([1, 2, 3, 4, 5], dtype=torch.uint8)

In [283]:
# ndarray 원소 변경
data[0] = 100

In [287]:
# from_numpy(), as_tensor() ==> 데이터 공유
# tensor() ==> 복사본 생성
data, t1, t2, t3


(array([100,   2,   3,   4,   5], dtype=uint8),
 tensor([100,   2,   3,   4,   5], dtype=torch.uint8),
 tensor([100,   2,   3,   4,   5], dtype=torch.uint8),
 tensor([1, 2, 3, 4, 5], dtype=torch.uint8))

In [291]:
arange(10), arange(1,10), arange(1,10,3)

(tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]),
 tensor([1, 4, 7]))