## 행렬 곱셈 
- 피쳐와 가중치 연산에 활용
- tensor.matmul() 

In [1]:
from torch import *
import intel_extension_for_pytorch as ipex

In [2]:
data = tensor([[1,2,],[3,4]])
w = tensor([[1],[3]])

data @ w

tensor([[ 7],
        [15]])

In [3]:
# 원소 단위 곱셈 => 인덱스에 1:1 대응하도록 브로드케스팅
data.matmul(w)

tensor([[ 7],
        [15]])

행 x 열 : (행, _열_) x (_행_, 열)

In [4]:
# 행열단위 곱셈 => 행 x 열 : (행, 열) x (행, 열)
w = tensor([7])
w2 = tensor([[7],[8]])

data.matmul(w2)

tensor([[23],
        [53]])

In [5]:
w2.reshape((-1))

tensor([7, 8])