## 텐서 원소 / 요소 접근
- 인덱싱과 슬라이싱

In [1]:
from torch import *
import torch
import intel_extension_for_pytorch as ipex
import numpy as np

In [2]:
torch.__version__ 

'2.2.0+cu121'

In [3]:
manual_seed(100)
points = randn((3,2)) * 10
points

tensor([[  3.6066,  -2.8592],
        [ -3.9382,   2.4294],
        [-13.8332, -23.1344]])

In [4]:
# Tensor 원소 1개 접근
# 1행 2열 데이터 추출
points[0,1]

tensor(-2.8592)

In [5]:
# 1번 행 인덱스 부터 나머지 모든 행 추출
points[1:]

tensor([[ -3.9382,   2.4294],
        [-13.8332, -23.1344]])

In [6]:
# 마지막 행 마지막 열
points[-1,-1]

tensor(-23.1344)

In [7]:
points[None].shape

torch.Size([1, 3, 2])

- Broadcasting 연산




In [8]:
manual_seed(42)

t1 = FloatTensor([[1,2,3], [4,5,6]])
t2 = FloatTensor([[3],[4]])

t1 * t2, t1.shape, t2.shape, t1 + t2,


(tensor([[ 3.,  6.,  9.],
         [16., 20., 24.]]),
 torch.Size([2, 3]),
 torch.Size([2, 1]),
 tensor([[ 4.,  5.,  6.],
         [ 8.,  9., 10.]]))

In [9]:
#원소단위 연산 수행 메서드들
t1.add(t2), t1.mul(t2), t1.div(t2), t1.sub(t2), t1.pow(t2), t1.remainder(t2), t1.clamp(min=t2.max(), max=t2.min())

(tensor([[ 4.,  5.,  6.],
         [ 8.,  9., 10.]]),
 tensor([[ 3.,  6.,  9.],
         [16., 20., 24.]]),
 tensor([[0.3333, 0.6667, 1.0000],
         [1.0000, 1.2500, 1.5000]]),
 tensor([[-2., -1.,  0.],
         [ 0.,  1.,  2.]]),
 tensor([[1.0000e+00, 8.0000e+00, 2.7000e+01],
         [2.5600e+02, 6.2500e+02, 1.2960e+03]]),
 tensor([[1., 2., 0.],
         [0., 1., 2.]]),
 tensor([[3., 3., 3.],
         [3., 3., 3.]]))