### softmax() , sigmoid() 함수 
<hr>

- sigmoid() : $ y = wx + b $ 결과 1개를 전달 ==> 반환 : 0.0 ~ 1.0 사이 값으로 변환
    * => 이진분류
- softmax() : $ y = \frac{e^{wx + b}}{\sum_{i=1}^{n}e^{w_ix_i + b_i}}$ 결과를 여러개 전달 ==> 반환 : 여러개의 결과값의 합이 1.0 이 되도록 변환
    * => 다중분류

In [3]:
import torch                    # 파이토치 기본 모듈로 텐서 및 기본 함수들
import torch.nn.functional as F # 파이토치 인공신경망 관련 함수
try:
    import intel_extension_for_pytorch as ipex
except:
    pass

In [13]:
data1 = torch.tensor([1.0, 2.0, 3.0, 1.1,2.2], dtype=torch.float32)
data1.shape

torch.Size([5])

In [14]:
F.sigmoid(data1)
data1.unsqueeze_(1)

tensor([[1.0000],
        [2.0000],
        [3.0000],
        [1.1000],
        [2.2000]])

In [20]:
input = torch.randn(2,5)
input

tensor([[ 0.6981, -0.0644,  0.2611, -1.2345,  0.4600],
        [-0.9148,  0.5164,  1.7515,  1.2003, -0.7133]])

In [27]:
F.softmax(input, dim=1), F.softmax(input, dim=0)

(tensor([[0.3284, 0.1532, 0.2121, 0.0475, 0.2588],
         [0.0344, 0.1438, 0.4947, 0.2851, 0.0421]]),
 tensor([[0.8338, 0.3588, 0.1838, 0.0806, 0.7637],
         [0.1662, 0.6412, 0.8162, 0.9194, 0.2363]]))

In [18]:
F.softmax(data1, dim=0), F.softmax(data1, dim=1)

(tensor([[0.0644],
         [0.1750],
         [0.4757],
         [0.0712],
         [0.2138]]),
 tensor([[1.],
         [1.],
         [1.],
         [1.],
         [1.]]))